name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for Hugging Face syncing

      # Step 2: Add Hugging Face remote
      - name: Add remote
        env:
          HF: ${{ secrets.HF }} # Hugging Face token stored in GitHub Secrets
        run: |
          git remote add space https://$HF@huggingface.co/spaces/lahiru676/hugging-face-demo2
          git push space main

      # Step 3: Verify Sync (Optional)
      - name: Verify Push to Hugging Face
        run: echo "Successfully synced to Hugging Face Hub."

